-- Auto-generated by tools/truthify.py
namespace LightLanguageTruth

def topTokens : List Nat := [14, 5, 13]
def zWindowsMeanApprox : Int := -7 -- scaled by 1e4
def zWindowsVarApprox  : Int := 0 -- scaled by 1e4

theorem CoercivePlaceholder : True := True.intro
theorem ExclusivityPlaceholder : True := True.intro

end LightLanguageTruth