-- Auto-generated by tools/truthify.py
namespace LightLanguageTruth

def topTokens : List Nat := [9, 15, 14]
def zWindowsMeanApprox : Int := 19 -- scaled by 1e4
def zWindowsVarApprox  : Int := 1 -- scaled by 1e4

theorem CoercivePlaceholder : True := True.intro
theorem ExclusivityPlaceholder : True := True.intro

end LightLanguageTruth